### ISSUE TITLE
Doesn't have access to directory

### ISSUE THREAD

**Issue by kaziamov** [crschnick/pdx_unlimiter#100]
java.io.IOException: Unable to access directory C:\Users\482\Documents. Please make sure that you have the appropriate permissions and no Antivirus program is blocking the access. In case you use cloud storage, verify that your cloud storage is working and you are logged in.
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.PdxuInstallation.checkDataDirectoryPermissions(PdxuInstallation.java:80)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.ComponentManager.initialSetup(ComponentManager.java:31)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.cli.MainCommand.run(MainCommand.java:34)
	at info.picocli/picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at info.picocli/picocli.CommandLine.access$1300(CommandLine.java:145)
	at info.picocli/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at info.picocli/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at info.picocli/picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at info.picocli/picocli.CommandLine.execute(CommandLine.java:2078)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.cli.MainCommand.main(MainCommand.java:29)

**Comment by crschnick** [comment]
Are you sure that for example the windows defender protections are off for pdxu? There are cases in which it blocks any directory access of an application.

**Comment by crschnick** [comment]
Closing this for now, I hope the issue has been resolved.
