### ISSUE TITLE
my file is too big

### ISSUE THREAD

**Issue by redxkiller45** [crschnick/pdx_unlimiter#103]
i want to remove some mods in savefile but it wont open 

it keeps giving me this 

java.lang.IllegalArgumentException: Input data size is too large. (Greater than 400MB)
	at com.crschnick.pdxu.editor/com.crschnick.pdxu.editor.target.SavegameEditTarget.parse(SavegameEditTarget.java:53)
	at com.crschnick.pdxu.editor/com.crschnick.pdxu.editor.target.ExternalEditTarget.parse(ExternalEditTarget.java:56)
	at com.crschnick.pdxu.editor/com.crschnick.pdxu.editor.Editor.lambda$createNewEditor$5(Editor.java:79)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by crschnick** [comment]
Which game is this about? Because if it is something like VIC3, then the process of removing mods is very complicated in this situation.
