### ISSUE TITLE
PDX wont start

### ISSUE THREAD

**Issue by danielfinans** [crschnick/pdx_unlimiter#111]
Updated windows and now PDX wont work.  
Tried uninstalling and re-installing.
Tried running the standalone version, same error. 
Tried manually deleting all related folders, and installing fresh. 

![image](https://github.com/crschnick/pdx_unlimiter/assets/43092606/738db459-ef3b-4250-985c-37ebcc689b15)

![image](https://github.com/crschnick/pdx_unlimiter/assets/43092606/382021c6-3bc9-408a-99e3-cf34bae4177e)

> com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in VALUE_STRING
>  at [Source: (File); line: 91, column: 63]
> 	at com.fasterxml.jackson.core@2.13.0/com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:682)
> 	at com.fasterxml.jackson.core@2.13.0/com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:663)
> 	at com.fasterxml.jackson.core@2.13.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMoreGuaranteed(UTF8StreamJsonParser.java:2444)
> 	at com.fasterxml.jackson.core@2.13.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2527)
> 	at com.fasterxml.jackson.core@2.13.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2507)
> 	at com.fasterxml.jackson.core@2.13.0/com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:334)
> 	at com.fasterxml.jackson.databind@2.13.0/com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:524)
> 	at com.fasterxml.jackson.databind@2.13.0/com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:84)
> 	at com.fasterxml.jackson.databind@2.13.0/com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:20)
> 	at com.fasterxml.jackson.databind@2.13.0/com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
> 	at com.fasterxml.jackson.databind@2.13.0/com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4717)
> 	at com.fasterxml.jackson.databind@2.13.0/com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3109)
> 	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.util.JsonHelper.read(JsonHelper.java:47)
> 	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.loadData(SavegameStorage.java:268)
> 	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.init(SavegameStorage.java:202)
> 	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.ComponentManager.init(ComponentManager.java:134)
> 	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
> 	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by danielfinans** [comment]
crschnick — 13:33
That is caused by data corruption of the storage config file
if you go to <documents directory>\Pdx-Unlimiter\savegames, there should be a campaigns.json file in the folders of games that you play 
it sadly doesn't tell which game this is about

Deleted the folder, reinstalled PDX, now working. Closing issue.
