### ISSUE TITLE
PDX unlimiter won't work after the update

### ISSUE THREAD

**Issue by artol96** [crschnick/pdx_unlimiter#114]
PDX unlimiter won't work after the update. I can not import any save game. I uninstalled and reinstalled the program but error continues.

java.io.IOException: Cannot run program "C:\Users\tolga\AppData\Local\Programs\Pdx-Unlimiter\app\resources\bin\rakaly_windows.exe": CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.util.integration.RakalyHelper.toEquivalentPlaintext(RakalyHelper.java:46)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.importSavegameData(SavegameStorage.java:672)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.importSavegame(SavegameStorage.java:601)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.FileImportTarget$StandardImportTarget.lambda$importTarget$0(FileImportTarget.java:244)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: CreateProcess error=2, Sistem belirtilen dosyayı bulamıyor
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 12 more

**Comment by crschnick** [comment]
Yeah I have seen that a few times. It is usually caused by Windows Defender or another AntiVirus program removing the melter executable because it thinks it's malicious.

You can try deleting `C:\Users\tolga\AppData\Local\Programs\Pdx-Unlimiter\app\` and relaunching pdxu. That should trigger a new download. If the file then gets removed again, you probably have to add an exception to your antivirus.

**Comment by artol96** [comment]
That worked. Thank you!!
