### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Oleksandrigo** [crschnick/pdx_unlimiter#127]
I get this error

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.io.InputStream.readNBytes(InputStream.java:448)
	at java.base/java.util.zip.ZipInputStream.readNBytes(ZipInputStream.java:274)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:349)
	at java.base/java.util.zip.ZipInputStream.readAllBytes(ZipInputStream.java:234)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.savegame.ZipSavegameStructure.parseInput(ZipSavegameStructure.java:67)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.savegame.ModernHeaderCompressedSavegameStructure.parse(ModernHeaderCompressedSavegameStructure.java:89)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.loadEntry(SavegameStorage.java:462)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameActions.lambda$reloadSavegame$15(SavegameActions.java:196)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameActions$$Lambda/0x000000002364f458.accept(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameContext.withSavegameContext(SavegameContext.java:92)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameActions.lambda$reloadSavegame$16(SavegameActions.java:192)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameActions$$Lambda/0x000000002364f238.run(Unknown Source)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor$$Lambda/0x00000000233fa858.call(Unknown Source)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor$$Lambda/0x00000000233faca0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.runWith(Thread.java:1596)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

[Магистр_Алекс_(Regula_Magistri_-_Британияий_Регула_Магистри)_907_10_27.zip](https://github.com/user-attachments/files/16895889/_._.Regula_Magistri_-_._._._907_10_27.zip)

**Comment by Oleksandrigo** [comment]
I just changed one setting in the game rules and hit save.

**Comment by crschnick** [comment]
Does that happen every time, e.g. also when you restart pdxu?

**Comment by Oleksandrigo** [comment]
Well, to change what I wanted had to restart the program and re-import the safe and re-turn the changes. I think there was an error, but it changed it.

**Comment by Oleksandrigo** [comment]
However, now a new safe (later) can not import at all
![image](https://github.com/user-attachments/assets/ec75f6c4-b601-4c80-8648-c089d1c13280)

**Comment by crschnick** [comment]
Is your system maybe just running out of RAM?

**Comment by Oleksandrigo** [comment]
16Gb RAM?

**Comment by crschnick** [comment]
Do you have any environment variable set like _JAVA_OPTIONS?

**Comment by Oleksandrigo** [comment]
![image](https://github.com/user-attachments/assets/56d577f0-61d9-4e98-8829-efca291e8545)
omg...

**Comment by crschnick** [comment]
Yes you need to remove that, otherwise it will only use 1gb

**Comment by Oleksandrigo** [comment]
Set to 4Gb and this work... Thanks =)
