### ISSUE TITLE
Manual Saves Trip Java Exception in Zip Function

### ISSUE THREAD

**Issue by mchappee** [crschnick/pdx_unlimiter#132]
Opening a non-autosave yields this error:

java.util.zip.ZipException: invalid bit length repeat
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:412)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:412)
	at java.base/java.util.zip.ZipInputStream.readNBytes(ZipInputStream.java:274)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:349)
	at java.base/java.util.zip.ZipInputStream.readAllBytes(ZipInputStream.java:234)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.savegame.ZipSavegameStructure.parseInput(ZipSavegameStructure.java:67)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.savegame.ModernHeaderCompressedSavegameStructure.parse(ModernHeaderCompressedSavegameStructure.java:89)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.importSavegameData(SavegameStorage.java:679)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.importSavegame(SavegameStorage.java:601)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.FileImportTarget$StandardImportTarget.lambda$importTarget$0(FileImportTarget.java:244)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by crschnick** [comment]
Can you share the save?

**Comment by mchappee** [comment]
I didn't change or see any settings that would have modified how CK3 saves the file.  I currently can't save from PDX-Unlimited because the game files are "read-only", though they are not read-only on disk.  (see attached)
![CK3-reeadonly](https://github.com/user-attachments/assets/b2229188-615c-4d9a-b8c1-4dba4e9da4ea)

**Comment by crschnick** [comment]
That means that they are ironman encrypted. If you click on the melt button, it should create an editable copy.

**Comment by mchappee** [comment]
Sorry, I didn't mean to hijack the initial problem of the Zip functionality, but thanks for the tip.  The autosaves import correctly, but the manual saves throw the Zip exception.  No external modifications required.  CK3 1.14.1 from Steam.  Mac OSX 15.1 on Apple silicon with M4 processor.

**Comment by crschnick** [comment]
And that Zip error happens for all manual saves?
