### ISSUE TITLE
Exception while trying to trash CK3 save

### ISSUE THREAD

**Issue by jzebedee** [crschnick/pdx_unlimiter#17]
Fresh install and first-run. Only CK3 (steam version) is installed and the folder was auto-detected correctly.

Repro:

1. Click "Import Savegames"
2. Click the bin / trash icon next to a savegame

```
java.lang.IllegalStateException: Not on FX application thread; currentThread = com.crschnick.pdx_unlimiter.app.game.Ck3Installation savegame watcher
	at javafx.graphics/com.sun.javafx.tk.Toolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.remove(Unknown Source)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.remove(Unknown Source)
	at javafx.controls/javafx.scene.control.DialogPane$5.invalidated(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at javafx.controls/javafx.scene.control.DialogPane.setContent(Unknown Source)
	at com.crschnick.pdx_unlimiter.app@2.0-beta11/com.crschnick.pdx_unlimiter.app.gui.GuiImporter.lambda$createImporterDialog$2(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at com.crschnick.pdx_unlimiter.app@2.0-beta11/com.crschnick.pdx_unlimiter.app.game.GameInstallation.lambda$initOptional$0(Unknown Source)
	at com.crschnick.pdx_unlimiter.app@2.0-beta11/com.crschnick.pdx_unlimiter.app.util.WatcherHelper.lambda$startWatcher$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by jzebedee** [comment]
![image](https://user-images.githubusercontent.com/1896945/101801236-008cc480-3b06-11eb-9f97-ef6745c9fc91.png)

**Comment by crschnick** [comment]
Thanks for the report, will be a quick fix for the next release
