### ISSUE TITLE
CK3 Save Game Import fails on 1.5 "Fleur-de-Lis"

### ISSUE THREAD

**Issue by awbooze** [crschnick/pdx_unlimiter#74]
I'm getting the following error trying to load a new Ironman save in the new 1.5 "Fleur-de-Lis" version of Crusader Kings III.

```
com.crschnick.pdxu.model.SavegameInfoException: Could not create savegame info of savegame
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3SavegameInfo.fromSavegame(Ck3SavegameInfo.java:53)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.lambda$init$4(SavegameStorage.java:125)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage$8.success(SavegameStorage.java:750)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.savegame.SavegameParseResult$Success.visit(SavegameParseResult.java:32)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.importSavegameData(SavegameStorage.java:744)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.SavegameStorage.importSavegame(SavegameStorage.java:636)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.savegame.FileImportTarget$StandardImportTarget.lambda$importTarget$0(FileImportTarget.java:231)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$2(TaskExecutor.java:70)
	at com.crschnick.pdxu.app/com.crschnick.pdxu.app.core.TaskExecutor.lambda$submitTask$4(TaskExecutor.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: "2.010000"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.node.ValueNode.getInteger(ValueNode.java:103)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms$Emblem.lambda$fromColoredEmblemNode$11(Ck3CoatOfArms.java:261)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms$Emblem.lambda$fromColoredEmblemNode$12(Ck3CoatOfArms.java:260)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms$Emblem.fromColoredEmblemNode(Ck3CoatOfArms.java:264)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms$Sub.subInstance(Ck3CoatOfArms.java:103)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms$Sub.fromNode(Ck3CoatOfArms.java:82)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms.fromNode(Ck3CoatOfArms.java:37)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms.lambda$createCoaMap$0(Ck3CoatOfArms.java:29)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.node.SimpleArrayNode.lambda$forEach$0(SimpleArrayNode.java:151)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.node.SimpleArrayNode.forEach(SimpleArrayNode.java:189)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.node.SimpleArrayNode.forEach(SimpleArrayNode.java:150)
	at com.crschnick.pdxu.io/com.crschnick.pdxu.io.node.Node.forEach(Node.java:16)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3CoatOfArms.createCoaMap(Ck3CoatOfArms.java:28)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3Tag.fromNode(Ck3Tag.java:107)
	at com.crschnick.pdxu.model/com.crschnick.pdxu.model.ck3.Ck3SavegameInfo.fromSavegame(Ck3SavegameInfo.java:37)
	... 13 more
```
Looks like a coat of arms parsing issue. Let me know if you need more information on this from me!

**Comment by crschnick** [comment]
Should be fixed in 1e9f5834db423d2ceca2a8fe24e7b6a1ad20df85.

I plan to push a new release with the fixes soon.

**Comment by crschnick** [comment]
I uploaded an experimental build here: https://github.com/crschnick/pdxu_achievements/releases/download/2.9.6/pdx_unlimiter-windows.zip

It is still not ready for a full release as the Ironman converters need to be updated for the new version as well

**Comment by crschnick** [comment]
The release is live

**Comment by awbooze** [comment]
Thanks for the response and your work on the project as a whole!
